// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Z288tnWnNvCQeMtXgSBb1ZnAfRaRNh0',
    appId: '1:395144911307:web:ee25ed0c2258672269be4e',
    messagingSenderId: '395144911307',
    projectId: 'crud-31bf0',
    authDomain: 'crud-31bf0.firebaseapp.com',
    storageBucket: 'crud-31bf0.appspot.com',
    measurementId: 'G-KDNDE68M8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vHLJwHVhUD96YjsCCSyye0W7weYHVTY',
    appId: '1:395144911307:android:b9344ece6b24b6c969be4e',
    messagingSenderId: '395144911307',
    projectId: 'crud-31bf0',
    storageBucket: 'crud-31bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaSy_SnCKWL00iPatbZMk3NQNP_LPjj-E',
    appId: '1:395144911307:ios:549f74de9f78df6a69be4e',
    messagingSenderId: '395144911307',
    projectId: 'crud-31bf0',
    storageBucket: 'crud-31bf0.appspot.com',
    iosBundleId: 'com.FIKRI140702.crud',
  );
}
